// Авторизация
PUT http://localhost:8080/create-post
Content-Type: application/json
token: $2a$08$a3vc3FNjPPqDIb0NO4dq3OUdvLrX4lu.0YNbgDLxh61VCup/eozJG

{
  "name": "Щетка для машины",
  "description": "Просто щетка",
  "price": 100,
  "image": "asdasdsad"
}
